[package]
name = "git-mit-config"
version = "5.13.30"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[dependencies]
mit-lint = "3.2.8"
shell-words = "1.1.0"
thiserror = "1.0.63"
miette = { version = "7.2.0", features = [ "fancy" ] }
git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }
clap_complete = "4.5.23"
clap = { version = "4.5.16", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }

comfy-table = "7.1.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.13.30"

[dev-dependencies]
indoc = "2.0.5"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.13.30"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
