[package]
name = "git-mit-config"
version = "5.12.1"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[dependencies]
mit-lint = "3.0.2"
shell-words = "1.0.0"
thiserror = "1.0.30"
miette = { version = "3.2.0", features = [ "fancy" ] }
git2 = "0.13.23"
openssl = { version = "0.10.38", optional = true }
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"

comfy-table = "4.1.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.1"

[dev-dependencies]
indoc = "1.0.3"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.1"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
