[package]
name = "git-mit-config"
version = "3.96.4"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0 1.0 Universal"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
tinytemplate = "1.1.0"
serde_json = "1.0.57"
serde_derive = "1.0.114"

  [build-dependencies.serde]
  version = "1.0.114"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

  [build-dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dependencies]
xdg = "2.2.0"
thiserror = "1.0.20"
git2 = "0.13.8"
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
console = "0.11.3"
comfy-table = "1.0.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "1.0.2"
pretty_assertions = "0.6.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
