[package]
name = "git-mit-config"
version = "5.12.146"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[dependencies]
mit-lint = "3.2.3"
shell-words = "1.1.0"
thiserror = "1.0.39"
miette = { version = "5.6.0", features = [ "fancy" ] }
git2 = "0.16.1"
openssl = { version = "0.10.52", optional = true }
clap_complete = "4.1.4"
clap = { version = "4.1.8", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }

comfy-table = "6.1.4"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.146"

[dev-dependencies]
indoc = "2.0.1"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.146"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
