[package]
name = "git-mit-config"
version = "5.12.76"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[dependencies]
mit-lint = "3.1.1"
shell-words = "1.1.0"
thiserror = "1.0.32"
miette = { version = "5.2.0", features = [ "fancy" ] }
git2 = "0.14.4"
openssl = { version = "0.10.41", optional = true }
clap_complete = "3.2.3"
clap = { version = "3.2.16", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }

comfy-table = "6.0.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.76"

[dev-dependencies]
indoc = "1.0.7"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.76"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
