[package]
name = "git-mit-config"
version = "5.6.5"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[build-dependencies]
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.4"
tinytemplate = "1.2.1"
serde_json = "1.0.68"
serde_derive = "1.0.125"
mit-lint = "0.2.0"

  [build-dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.6.5"

  [build-dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.6.5"

[dependencies]
mit-lint = "0.2.0"
shell-words = "1.0.0"
xdg = "2.2.0"
thiserror = "1.0.29"
git2 = "0.13.22"
openssl = { version = '0.10', optional = true }
clap = "3.0.0-beta.4"
clap_derive = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
console = "0.14.1"
comfy-table = "4.1.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.6.5"

[dev-dependencies]
indoc = "1.0.3"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.6.5"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
