[package]
name = "git-mit-config"
version = "5.12.27"
authors = [ "Billie Thompson <billie+git-mit-config@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "A command for enabling and disabling git lints"

[dependencies]
mit-lint = "3.0.3"
shell-words = "1.0.0"
thiserror = "1.0.30"
miette = { version = "3.3.0", features = [ "fancy" ] }
git2 = "0.13.25"
openssl = { version = "0.10.38", optional = true }
clap_complete = "3.0.5"
clap = { version = "3.0.13", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }

comfy-table = "5.0.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.27"

[dev-dependencies]
indoc = "1.0.3"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.27"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
