[package]
name = "mit-commit-message-lints"
version = "5.12.6"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.0.0"
time = { version = "0.3.5", features = ["local-offset"] }
glob = "0.3.0"
thiserror = "1.0.30"
miette = { version = "3.2.0", features = [ "fancy" ] }
git2 = "0.13.24"
openssl = { version = "0.10.38", optional = true }
regex = "1.5.4"
serde_yaml = "0.8.21"
serde_derive = "1.0.130"
indoc = "1.0.3"
toml = "0.5.8"
mit-commit = "3.0.0"
mit-lint = "3.0.2"
comfy-table = "4.1.1"
clap_generate = "3.0.0-beta.5"
clap = "3.0.0-beta.5"
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

  [dependencies.serde]
  version = "1.0.130"
  features = [ "derive" ]

[dev-dependencies]
criterion = "0.3.5"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.6"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
