[package]
name = "mit-commit-message-lints"
version = "5.12.114"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.1.0"
time = { version = "0.3.17", features = ["local-offset"] }
glob = "0.3.0"
thiserror = "1.0.37"
miette = { version = "5.4.1", features = [ "fancy" ] }
git2 = "0.15.0"
openssl = { version = "0.10.43", optional = true }
regex = "1.7.0"
serde_yaml = "0.9.14"
serde_derive = "1.0.147"
indoc = "1.0.7"
toml = "0.5.9"
mit-commit = "3.1.4"
mit-lint = "3.2.2"
comfy-table = "6.1.3"
clap_complete = "4.0.6"
clap = { version = "4.0.29", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

  [dependencies.serde]
version = "1.0.147"
features = [ "derive" ]

[dev-dependencies]
criterion = "0.4.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.114"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
