[package]
name = "mit-commit-message-lints"
version = "3.98.69"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
rayon = "1.5.0"
glob = "0.3.0"
thiserror = "1.0.24"
git2 = "0.13.17"
regex = "1.4.5"
serde_yaml = "0.8.17"
serde_derive = "1.0.125"
indoc = "1.0.3"
toml = "0.5.8"
mit-commit = "1.29.7"
lazy_static = "1.4.0"
console = "0.14.1"
comfy-table = "2.1.0"

  [dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

[dev-dependencies]
pretty_assertions = "0.7.1"
criterion = "0.3.4"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"

[[bench]]
name = "linting"
harness = false

[[bench]]
name = "trailers"
harness = false
