[package]
name = "mit-commit-message-lints"
version = "5.13.1"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.1.0"
time = { version = "0.3.36", features = ["local-offset"] }
glob = "0.3.1"
thiserror = "1.0.63"
miette = { version = "7.2.0", features = [ "fancy" ] }
git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }
regex = "1.10.5"
serde_yaml = "0.9.34"
serde_derive = "1.0.204"
indoc = "2.0.5"
toml = "0.8.16"
mit-commit = "3.2.0"
mit-lint = "3.2.8"
comfy-table = "7.1.1"
clap_complete = "4.5.11"
clap = { version = "4.5.11", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

  [dependencies.serde]
version = "1.0.204"
features = [ "derive" ]

[dev-dependencies]
criterion = "0.5.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.13.1"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
