[package]
name = "mit-commit-message-lints"
version = "5.7.4"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
rayon = "1.5.1"
glob = "0.3.0"
thiserror = "1.0.29"
git2 = "0.13.22"
openssl = { version = '0.10', optional = true }
regex = "1.5.4"
serde_yaml = "0.8.21"
serde_derive = "1.0.125"
indoc = "1.0.3"
toml = "0.5.8"
mit-commit = "1.29.9"
mit-lint = "0.2.0"
console = "0.14.1"
comfy-table = "4.1.1"

  [dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

[dev-dependencies]

criterion = "0.3.5"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.7.4"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
