[package]
name = "mit-commit-message-lints"
version = "5.11.2"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.0.0"
chrono = "0.4.19"
glob = "0.3.0"
thiserror = "1.0.29"
miette = { version = "3.2.0", features = [ "fancy" ] }
git2 = "0.13.23"
openssl = { version = '0.10', optional = true }
regex = "1.5.4"
serde_yaml = "0.8.21"
serde_derive = "1.0.125"
indoc = "1.0.3"
toml = "0.5.8"
mit-commit = "1.33.2"
mit-lint = "2.2.4"
comfy-table = "4.1.1"
clap_generate = "3.0.0-beta.2"
clap = "3.0.0-beta.4"
quickcheck_macros = "1"
quickcheck = "1"

  [dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

[dev-dependencies]
criterion = "0.3.5"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.11.2"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
