[package]
name = "mit-commit-message-lints"
version = "3.97.1"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0 1.0 Universal"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
rayon = "1.1"
glob = "0.3.0"
thiserror = "1.0.20"
git2 = "0.13.8"
regex = "1.3.9"
serde_yaml = "0.8.13"
serde_derive = "1.0.114"
indoc = "1.0.2"
toml = "0.5.6"
mit-commit = "1.10.0"
lazy_static = "1.4.0"
console = "0.12.0"
comfy-table = "1.0.0"

  [dependencies.serde]
  version = "1.0.115"
  features = [ "derive" ]

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3.3"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"

[[bench]]
name = "linting"
harness = false

[[bench]]
name = "trailers"
harness = false
