[package]
name = "mit-commit-message-lints"
version = "5.12.74"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.1.0"
time = { version = "0.3.11", features = ["local-offset"] }
glob = "0.3.0"
thiserror = "1.0.31"
miette = { version = "5.2.0", features = [ "fancy" ] }
git2 = "0.14.4"
openssl = { version = "0.10.41", optional = true }
regex = "1.6.0"
serde_yaml = "0.8.26"
serde_derive = "1.0.138"
indoc = "1.0.7"
toml = "0.5.9"
mit-commit = "3.1.2"
mit-lint = "3.1.1"
comfy-table = "6.0.0"
clap_complete = "3.2.3"
clap = { version = "3.2.15", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

  [dependencies.serde]
version = "1.0.138"
features = [ "derive" ]

[dev-dependencies]
criterion = "0.3.6"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.74"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
