[package]
name = "mit-commit-message-lints"
version = "5.12.144"
authors = [
  "Billie Thompson <billie+mit-commit-message-lints@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Check the correctness of a specific commit message. Designed to be used in tools providing commit-msg style hooks"

[dependencies]
shell-words = "1.1.0"
time = { version = "0.3.20", features = ["local-offset"] }
glob = "0.3.1"
thiserror = "1.0.39"
miette = { version = "5.5.0", features = [ "fancy" ] }
git2 = "0.16.1"
openssl = { version = "0.10.45", optional = true }
regex = "1.7.1"
serde_yaml = "0.9.19"
serde_derive = "1.0.153"
indoc = "2.0.1"
toml = "0.7.2"
mit-commit = "3.1.6"
mit-lint = "3.2.3"
comfy-table = "6.1.4"
clap_complete = "4.1.4"
clap = { version = "4.1.8", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

  [dependencies.serde]
version = "1.0.153"
features = [ "derive" ]

[dev-dependencies]
criterion = "0.4.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.144"

[[bench]]
name = "trailers"
harness = false

[features]
default = []
vendored-openssl = ["openssl/vendored"]
