version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: "scope"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: build
      include: "scope"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      include: "scope"
