use_angular: true
types: [ci]
scopes:
    [
        "deps",
        "deploy",
        "Mergify",
        "Actions",
        "Homebrew",
        "FastConventional",
        "Justfile",
        "src",
        "Changelog",
    ]
