queue_rules:
- name: default
  conditions:
  - status-success=lints
  - status-success=specdown (ubuntu-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-...
  - status-success=specdown (macos-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-x...
  - status-success=bench (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
    libxcb-xfixes0-dev)
  - status-success=bench (macos-latest, echo nothing-to-install)
  - status-success=version
  - status-success=test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
    libxcb-xfixes0-dev)
  - status-success=test (macos-latest, echo nothing-to-install)
  - status-success=security-audit
  - status-success=check

pull_request_rules:
- name: request review on external contributor
  conditions:
  - -author=PurpleBooth
  actions:
    request_reviews:
      users:
      - PurpleBooth

- name: automatic rebase for dependencies
  conditions:
  - status-success=lints
  - status-success=specdown (ubuntu-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-...
  - status-success=specdown (macos-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-x...
  - status-success=bench (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
    libxcb-xfixes0-dev)
  - status-success=bench (macos-latest, echo nothing-to-install)
  - status-success=version
  - status-success=test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
    libxcb-xfixes0-dev)
  - status-success=test (macos-latest, echo nothing-to-install)
  - status-success=security-audit
  - status-success=check
  - base=main
  - label=dependencies
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
