queue_rules:
  - name: default
    speculative_checks: 20
    batch_size: 20
    conditions:
      - check-success=docker-build / docker-build
      - check-success=lint-markdown / lint-markdown
      - check-success=rust-check / test (macos-latest)
      - check-success=rust-check / test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev)
      - check-success=rust-check / test (windows-latest)
      - check-success=rust-check / lints (macos-latest)
      - check-success=rust-check / lints (ubuntu-latest)
      - check-success=rust-check / lints (windows-latest)
      - check-success=rust-check / security-audit
      - check-success=rust-check / bench (macos-latest)
      - check-success=rust-check / bench (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev)
      - check-success=rust-check / bench (windows-latest)
      - check-success=specdown / specdown (macos-latest)
      - check-success=specdown / specdown (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommo...
      - check-success=specdown / specdown (windows-latest)

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - check-success=docker-build / docker-build
      - check-success=lint-markdown / lint-markdown
      - check-success=rust-check / test (macos-latest)
      - check-success=rust-check / test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev)
      - check-success=rust-check / test (windows-latest)
      - check-success=rust-check / lints (macos-latest)
      - check-success=rust-check / lints (ubuntu-latest)
      - check-success=rust-check / lints (windows-latest)
      - check-success=rust-check / security-audit
      - check-success=rust-check / bench (macos-latest)
      - check-success=rust-check / bench (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev)
      - check-success=rust-check / bench (windows-latest)
      - check-success=specdown / specdown (macos-latest)
      - check-success=specdown / specdown (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommo...
      - check-success=specdown / specdown (windows-latest)
      - base=main
      - label=dependencies
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        name: default
