queue_rules:
  - name: default
    speculative_checks: 20
    batch_size: 20
    conditions:
      - status-success~=^docker-build
      - status-success~=^lint-markdown
      - status-success~=^specdown
      - status-success~=^version
      - status-success~=^rust-check

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - status-success~=^docker-build
      - status-success~=^lint-markdown
      - status-success~=^specdown
      - status-success~=^version
      - status-success~=^rust-check
      - base=main
      - label=dependencies
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
