options:
    prev_tag: versio-prev

projects:
    - name: git-mit
      id: 1
      tag_prefix: ""
      labels: cargo
      version:
          file: git-mit/Cargo.toml
          toml: package.version
      also:
          - file: ./docs/binaries/git-mit.md
            pattern: git-mit (\d+\.\d+\.\d+)
          - file: ./docs/binaries/git-mit-config.md
            pattern: git-mit-config (\d+\.\d+\.\d+)
          - file: ./docs/binaries/git-mit-install.md
            pattern: git-mit-install (\d+\.\d+\.\d+)
          - file: ./docs/binaries/git-mit-relates-to.md
            pattern: git-mit-relates-to (\d+\.\d+\.\d+)
          - file: ./docs/binaries/mit-commit-msg.md
            pattern: mit-commit-msg (\d+\.\d+\.\d+)
          - file: ./docs/binaries/mit-pre-commit.md
            pattern: mit-pre-commit (\d+\.\d+\.\d+)
          - file: ./docs/binaries/mit-prepare-commit-msg.md
            pattern: mit-prepare-commit-msg (\d+\.\d+\.\d+)
          - file: git-mit-config/Cargo.toml
            toml: package.version

          - file: git-mit-config/Cargo.toml
            toml: build-dependencies.mit-commit-message-lints.version
          - file: git-mit-config/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: git-mit/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: git-mit-install/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version

          - file: git-mit-config/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version
          - file: git-mit/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version
          - file: git-mit-install/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

          - file: git-mit-install/Cargo.toml
            toml: package.version

          - file: git-mit-relates-to/Cargo.toml
            toml: package.version
          - file: git-mit-relates-to/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: git-mit-relates-to/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

          - file: mit-commit-message-lints/Cargo.toml
            toml: package.version
          - file: mit-commit-message-lints/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

          - file: mit-commit-msg/Cargo.toml
            toml: package.version
          - file: mit-commit-msg/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: mit-commit-msg/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

          - file: mit-hook-test-helper/Cargo.toml
            toml: package.version

          - file: mit-pre-commit/Cargo.toml
            toml: package.version
          - file: mit-pre-commit/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: mit-pre-commit/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

          - file: mit-prepare-commit-msg/Cargo.toml
            toml: package.version
          - file: mit-prepare-commit-msg/Cargo.toml
            toml: dependencies.mit-commit-message-lints.version
          - file: mit-prepare-commit-msg/Cargo.toml
            toml: dev-dependencies.mit-hook-test-helper.version

      hooks:
          post_write: cargo check

sizes:
    use_angular: true
    minor: [revert]
    none: [ci, ignore, "-"]
