options:
  prev_tag: versio-prev

projects:
- name: git-mit
  id: 1
  tag_prefix: ''
  labels: cargo
  version:
    file: git-mit/Cargo.toml
    toml: package.version
  also:
  - file: git-mit-config/Cargo.toml
    toml: package.version
  - file: git-mit-install/Cargo.toml
    toml: package.version
  - file: git-mit-relates-to/Cargo.toml
    toml: package.version
  - file: mit-build-tools/Cargo.toml
    toml: package.version
  - file: mit-commit-message-lints/Cargo.toml
    toml: package.version
  - file: mit-commit-msg/Cargo.toml
    toml: package.version
  - file: mit-hook-test-helper/Cargo.toml
    toml: package.version
  - file: mit-pre-commit/Cargo.toml
    toml: package.version
  - file: mit-prepare-commit-msg/Cargo.toml
    toml: package.version
  hooks:
    post_write: cargo check

sizes:
  use_angular: true
  none: [ci]
