[workspace]

members = [
    "git-mit-config",
    "git-mit-install",
    "mit-prepare-commit-msg",
    "mit-pre-commit",
    "mit-commit-msg",
    "mit-commit-message-lints",
    "mit-hook-test-helper",
    "git-mit",
    "git-mit-relates-to",
]
