tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
    "cargo build --release",
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "git-mit"
owner = "PurpleBooth"

authors = []
