edition = "2018"

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
wrap_comments = true
normalize_comments = true
