unstable_features = true

condense_wildcard_suffixes = true
edition = "2018"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
reorder_modules = true
use_try_shorthand = true
wrap_comments = true
