[package]
name = "mit-commit-msg"
version = "5.13.9"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
mit-lint = "3.2.8"
clap_complete = "4.5.12"
clap = { version = "4.5.13", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }
miette = { version = "7.2.0", features = [ "fancy" ] }
mit-commit = "3.2.0"

arboard = "3.4.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.13.9"

[dev-dependencies]
indoc = "2.0.5"
tempfile = "3.11.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.13.9"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
