[package]
name = "mit-commit-msg"
version = "5.12.118"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
mit-lint = "3.2.2"
clap_complete = "4.0.6"
clap = { version = "4.0.30", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.15.0"
openssl = { version = "0.10.45", optional = true }
miette = { version = "5.5.0", features = [ "fancy" ] }
mit-commit = "3.1.4"

arboard = "3.2.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.118"

[dev-dependencies]
indoc = "1.0.8"
tempfile = "3.3.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.118"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
