[package]
name = "mit-commit-msg"
version = "5.12.164"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
mit-lint = "3.2.7"
clap_complete = "4.4.3"
clap = { version = "4.4.6", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.18.1"
openssl = { version = "0.10.45", optional = true }
miette = { version = "5.6.0", features = [ "fancy" ] }
mit-commit = "3.1.8"

arboard = "3.2.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.12.164"

[dev-dependencies]
indoc = "2.0.4"
tempfile = "3.4.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.12.164"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
