[package]
name = "mit-commit-msg"
version = "5.11.8"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
tinytemplate = "1.2.1"
serde_json = "1.0.68"
serde_derive = "1.0.130"

  [build-dependencies.serde]
  version = "1.0.130"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.11.8"

[dependencies]
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["full"] }
mit-lint = "3.0.0"
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
git2 = "0.13.23"
openssl = { version = "0.10.38", optional = true }
miette = { version = "3.2.0", features = [ "fancy" ] }
mit-commit = "2.0.0"

arboard = "2.0.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.11.8"

[dev-dependencies]
indoc = "1.0.3"
tempfile = "3.2.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.11.8"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
