[package]
name = "mit-commit-msg"
version = "3.98.18"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.1"
tinytemplate = "1.1.0"
serde_json = "1.0.58"
serde_derive = "1.0.114"

  [build-dependencies.serde]
  version = "1.0.116"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
clap = "3.0.0-beta.1"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.1"
git2 = "0.13.11"
thiserror = "1.0.20"
mit-commit = "1.15.0"
console = "0.12.0"
copypasta = "0.7.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "1.0.2"
tempfile = "3.1.0"
pretty_assertions = "0.6.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
