[package]
name = "mit-commit-msg"
version = "5.14.8"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "2.0.0"
tokio = { version = "1.43.0", features = ["full"] }
mit-lint = "3.2.9"
clap_complete = "4.5.42"
clap = { version = "4.5.26", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.20.0"
openssl = { version = "0.10.68", optional = true }
miette = { version = "7.4.0", features = [ "fancy" ] }
mit-commit = "3.2.1"

arboard = "3.4.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.14.8"

[dev-dependencies]
indoc = "2.0.5"
tempfile = "3.15.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.14.8"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
