[package]
name = "mit-commit-msg"
version = "3.98.73"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
tinytemplate = "1.2.1"
serde_json = "1.0.64"
serde_derive = "1.0.125"

  [build-dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "3.98.73"

[dependencies]
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
git2 = "0.13.17"
thiserror = "1.0.24"
mit-commit = "1.29.7"
console = "0.14.1"
copypasta = "0.7.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "3.98.73"

[dev-dependencies]
indoc = "1.0.3"
tempfile = "3.2.0"
pretty_assertions = "0.7.2"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "3.98.73"
