[package]
name = "mit-commit-msg"
version = "3.4.0"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/pb-git-hooks"

[dependencies]
clap = "3.0.0-beta.1"
git2 = "0.13"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "0.3"
tempfile = "3"
pretty_assertions = "0.6.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
