[package]
name = "mit-commit-msg"
version = "5.12.78"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
mit-lint = "3.1.1"
clap_complete = "3.2.4"
clap = { version = "3.2.17", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
git2 = "0.14.4"
openssl = { version = "0.10.41", optional = true }
miette = { version = "5.2.0", features = [ "fancy" ] }
mit-commit = "3.1.2"

arboard = "2.1.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.78"

[dev-dependencies]
indoc = "1.0.7"
tempfile = "3.3.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.78"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
