[package]
name = "mit-commit-msg"
version = "5.12.14"
authors = [ "Billie Thompson <billie+mit-commit-msg@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Validate the commit message that a user has input"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
mit-lint = "3.0.3"
clap_complete = "3.0.1"
clap = { version = "3.0.1", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
git2 = "0.13.25"
openssl = { version = "0.10.38", optional = true }
miette = { version = "3.2.0", features = [ "fancy" ] }
mit-commit = "3.0.0"

arboard = "2.0.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.14"

[dev-dependencies]
indoc = "1.0.3"
tempfile = "3.2.0"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.14"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
