[package]
name = "git-mit-relates-to"
version = "5.13.18"
authors = [
  "Billie Thompson <billie+git-mit-relates-to@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "Set Relates-to trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.63"
miette = { version = "7.2.0", features = [ "fancy" ] }
clap_complete = "4.5.13"
clap = { version = "4.5.16", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.13.18"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
indoc = "2.0.5"
tempfile = "3.11.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.13.18"
