[package]
name = "git-mit-relates-to"
version = "5.12.143"
authors = [
  "Billie Thompson <billie+git-mit-relates-to@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "Set Relates-to trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.38"
miette = { version = "5.5.0", features = [ "fancy" ] }
clap_complete = "4.1.4"
clap = { version = "4.1.8", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.16.1"
openssl = { version = "0.10.45", optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.143"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
indoc = "2.0.1"
tempfile = "3.4.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.143"
