[package]
name = "git-mit-relates-to"
version = "5.10.8"
authors = [
  "Billie Thompson <billie+git-mit-relates-to@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "Set Relates-to trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.4"
clap_derive = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.10.8"

[dependencies]
thiserror = "1.0.29"
miette = { version = "3.2.0", features = [ "fancy" ] }
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.4"
git2 = "0.13.23"
openssl = { version = '0.10', optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.10.8"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
indoc = "1.0.3"
tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.10.8"
