[package]
name = "git-mit-relates-to"
version = "5.12.186"
authors = [
  "Billie Thompson <billie+git-mit-relates-to@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "Set Relates-to trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
thiserror = "1.0.56"
miette = { version = "5.6.0", features = [ "fancy" ] }
clap_complete = "4.4.10"
clap = { version = "4.4.14", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.18.1"
openssl = { version = "0.10.63", optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.12.186"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
indoc = "2.0.4"
tempfile = "3.9.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.12.186"
