[package]
name = "git-mit-relates-to"
version = "3.99.4"
authors = [
  "Billie Thompson <billie+git-mit-relates-to@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "Set Relates-to trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "3.99.4"

[dependencies]
thiserror = "1.0.24"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
xdg = "2.2.0"
git2 = "0.13.19"
console = "0.14.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "3.99.4"

[dev-dependencies]
indoc = "1.0.3"
tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "3.99.4"
