[package]
name = "mit-build-tools"
version = "3.17.0"
authors = [
  "Billie Thompson <billie+mit-build-tools@billiecodes.com>"
]
edition = "2018"
license = "CC0 1.0 Universal"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "manpages", "completion" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Generate different things from a clap app file"

[dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
clap_derive = "3.0.0-beta.2"
xdg = "2.2.0"
tinytemplate = "1.1.0"
serde_json = "1.0.61"
serde_derive = "1.0.114"
console = "0.13.0"

  [dependencies.serde]
  version = "1.0.117"
  features = [ "derive" ]
