[package]
name = "mit-hook-test-helper"
version = "3.85.0"
authors = [
  "Billie Thompson <billie+mit-hook-test-helper@billiecodes.com>"
]
edition = "2018"
license = "CC0 1.0 Universal"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"
description = "Testing help tools for git-mit"

[dependencies]
tempfile = "3.1.0"
git2 = "0.13.6"
pretty_assertions = "0.6.1"
console = "0.11.3"
