[package]
name = "mit-prepare-commit-msg"
version = "3.97.1"
authors = [
  "Billie Thompson <billie+mit-prepare-commit-msg@billiecodes.com>"
]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "This hook is invoked by git-commit right after preparing the default log message, and before the editor is started."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
tinytemplate = "1.1.0"
serde_json = "1.0.57"
serde_derive = "1.0.114"

  [build-dependencies.serde]
  version = "1.0.114"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
thiserror = "1.0.20"
clap = "3.0.0-beta.1"
git2 = "0.13.8"
mit-commit = "1.10.0"
console = "0.12.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "1.0.2"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
