[package]
name = "mit-prepare-commit-msg"
version = "5.12.156"
authors = [
  "Billie Thompson <billie+mit-prepare-commit-msg@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "This hook is invoked by git-commit right after preparing the default log message, and before the editor is started."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
tinytemplate = "1.2.1"
thiserror = "1.0.49"
miette = { version = "5.6.0", features = [ "fancy" ] }
shell-words = "1.1.0"
clap_complete = "4.4.3"
clap = { version = "4.4.6", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.18.1"
openssl = { version = "0.10.45", optional = true }
mit-commit = "3.1.8"



  [dependencies.serde]
version = "1.0.153"
features = [ "derive" ]

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.12.156"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
indoc = "2.0.4"

tempfile = "3.4.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.12.156"
