[package]
name = "mit-prepare-commit-msg"
version = "5.12.112"
authors = [
  "Billie Thompson <billie+mit-prepare-commit-msg@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "This hook is invoked by git-commit right after preparing the default log message, and before the editor is started."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
tinytemplate = "1.2.1"
thiserror = "1.0.37"
miette = { version = "5.4.1", features = [ "fancy" ] }
shell-words = "1.1.0"
clap_complete = "4.0.5"
clap = { version = "4.0.26", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.15.0"
openssl = { version = "0.10.42", optional = true }
mit-commit = "3.1.4"



  [dependencies.serde]
version = "1.0.147"
features = [ "derive" ]

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.112"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
indoc = "1.0.7"

tempfile = "3.3.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.112"
