[package]
name = "mit-prepare-commit-msg"
version = "6.0.4"
authors = [
  "Billie Thompson <billie+mit-prepare-commit-msg@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "This hook is invoked by git-commit right after preparing the default log message, and before the editor is started."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
tinytemplate = "1.2.1"
thiserror = "2.0.0"
miette = { version = "7.4.0", features = [ "fancy" ] }
shell-words = "1.1.0"
clap_complete = "4.5.42"
clap = { version = "4.5.26", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
openssl = { version = "0.10.68", optional = true }
mit-commit = "3.3.1"



  [dependencies.serde]
version = "1.0.217"
features = [ "derive" ]

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "6.0.4"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
