[package]
name = "mit-prepare-commit-msg"
version = "5.11.8"
authors = [
  "Billie Thompson <billie+mit-prepare-commit-msg@billiecodes.com>"
]
edition = "2018"
license = "CC0-1.0"
description = "This hook is invoked by git-commit right after preparing the default log message, and before the editor is started."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
serde_json = "1.0.68"

  [build-dependencies.serde]
  version = "1.0.130"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.11.8"

[dependencies]
tinytemplate = "1.2.1"
thiserror = "1.0.30"
miette = { version = "3.2.0", features = [ "fancy" ] }
clap = "3.0.0-beta.5"
shell-words = "1.0.0"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
git2 = "0.13.23"
openssl = { version = "0.10.38", optional = true }
mit-commit = "3.0.0"



  [dependencies.serde]
  version = "1.0.130"
  features = [ "derive" ]

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.11.8"

[features]
default = []
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
indoc = "1.0.3"

tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.11.8"
