[package]
name = "git-mit"
version = "3.98.45"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
indoc = "1.0.3"
xdg = "2.2.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
indoc = "1.0.3"
thiserror = "1.0.23"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
xdg = "2.2.0"
git2 = "0.13.15"
console = "0.14.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
tempfile = "3.1.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
