[package]
name = "git-mit"
version = "5.9.7"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
indoc = "1.0.3"
xdg = "2.2.0"
clap = "3.0.0-beta.4"
clap_derive = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.9.7"

[dependencies]
shell-words = "1.0.0"
indoc = "1.0.3"
thiserror = "1.0.29"
miette = { version = "3.1.0", features = [ "fancy" ] }
clap = "3.0.0-beta.4"
clap_derive = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
xdg = "2.2.0"
git2 = "0.13.23"
openssl = { version = '0.10', optional = true }

mit-build-tools = { path = "../mit-build-tools" }

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.9.7"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.9.7"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
