[package]
name = "git-mit"
version = "5.12.62"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
shell-words = "1.1.0"
indoc = "1.0.6"
thiserror = "1.0.31"
miette = { version = "4.7.1", features = [ "fancy" ] }
clap_complete = "3.1.4"
clap = { version = "3.1.18", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
git2 = "0.14.4"
openssl = { version = "0.10.40", optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.62"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.3.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.62"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
