[package]
name = "git-mit"
version = "3.6.0"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/pb-git-hooks"

[dependencies]
clap = "3.0.0-beta.1"
xdg = "^2.1"
git2 = "0.13"
clap_generate = "3.0.0-beta.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "0.3"
tempfile = "3"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
