[package]
name = "git-mit"
version = "5.12.196"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
shell-words = "1.1.0"
indoc = "2.0.4"
thiserror = "1.0.57"
miette = { version = "5.6.0", features = [ "fancy" ] }
clap_complete = "4.5.0"
clap = { version = "4.5.0", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.18.2"
openssl = { version = "0.10.63", optional = true }


  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.12.196"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.10.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.12.196"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
