[package]
name = "git-mit"
version = "3.91.1"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Set author and Co-authored trailer."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
xdg = "2.2.0"
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
thiserror = "1.0.20"
clap = "3.0.0-beta.1"
xdg = "2.2.0"
git2 = "0.13.6"
clap_generate = "3.0.0-beta.1"
console = "0.11.3"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "0.3.6"
tempfile = "3.1.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
