[package]
name = "pb-pre-commit"
version = "2.1.0"
authors = ["Billie Thompson <billie+pb-pre-commit@billiecodes.com>"]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Run first, before you even type in a commit message. It’s used to inspect the snapshot that’s about to be committed."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
[dev-dependencies]
itertools = "0.9.0"
