[package]
name = "git-mit-install"
version = "5.12.146"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
which = "4.4.0"
thiserror = "1.0.39"
miette = { version = "5.6.0", features = [ "fancy" ] }
clap_complete = "4.3.1"
clap = { version = "4.1.8", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }


git2 = "0.16.1"
openssl = { version = "0.10.45", optional = true }

indoc = "2.0.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.146"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.4.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.146"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
