[package]
name = "git-mit-install"
version = "5.14.2"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
which = "7.0.0"
thiserror = "1.0.63"
miette = { version = "7.2.0", features = [ "fancy" ] }
clap_complete = "4.5.23"
clap = { version = "4.5.16", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }


git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }

indoc = "2.0.5"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.14.2"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.12.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.14.2"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
