[package]
name = "git-mit-install"
version = "5.12.8"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
which = "4.2.2"
thiserror = "1.0.30"
miette = { version = "3.2.0", features = [ "fancy" ] }
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-rc.3"


git2 = "0.13.25"
openssl = { version = "0.10.38", optional = true }

indoc = "1.0.3"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.8"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.8"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
