[package]
name = "git-mit-install"
version = "3.97.2"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
which = "4.0.2"
thiserror = "1.0.20"
clap = "3.0.0-beta.1"
xdg = "2.2.0"
git2 = "0.13.8"
clap_generate = "3.0.0-beta.1"
console = "0.12.0"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "1.0.2"
tempfile = "3.1.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
