[package]
name = "git-mit-install"
version = "5.12.38"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
which = "4.2.4"
thiserror = "1.0.30"
miette = { version = "4.2.1", features = [ "fancy" ] }
clap_complete = "3.1.0"
clap = { version = "3.1.3", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }


git2 = "0.14.1"
openssl = { version = "0.10.38", optional = true }

indoc = "1.0.4"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.38"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.3.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.38"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
