[package]
name = "git-mit-install"
version = "5.8.0"
authors = [ "Billie Thompson <billie+git-mit-install@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Install git-mit into a repository"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.4"

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "5.8.0"

[dependencies]
which = "4.2.2"
thiserror = "1.0.29"
miette = { version = "3.0.0", features = [ "fancy" ] }
clap = "3.0.0-beta.4"
clap_derive = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.2"
xdg = "2.2.0"
git2 = "0.13.22"
openssl = { version = '0.10', optional = true }
console = "0.14.1"
indoc = "1.0.3"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.8.0"

[dev-dependencies]
tempfile = "3.2.0"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.8.0"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
