[package]
name = "mit-pre-commit"
version = "3.85.0"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
tinytemplate = "1.1.0"
serde_json = "1.0.56"
serde_derive = "1.0.114"

  [build-dependencies.serde]
  version = "1.0.114"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"

[dependencies]
thiserror = "1.0.20"
clap = "3.0.0-beta.1"
git2 = "0.13.6"
mit-commit = "1.5.0"
console = "0.11.3"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "0.3.6"
pretty_assertions = "0.6.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
