[package]
name = "mit-pre-commit"
version = "5.13.3"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
time = "0.3.36"
thiserror = "1.0.63"
miette = { version = "7.2.0", features = [ "fancy" ] }
clap_complete = "4.5.11"
clap = { version = "4.5.11", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
git2 = "0.19.0"
openssl = { version = "0.10.66", optional = true }
mit-commit = "3.2.0"



  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
version = "5.13.3"

[features]
default = []
vendored-openssl = ["openssl/vendored"]


[dev-dependencies]
indoc = "2.0.5"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
version = "5.13.3"
