[package]
name = "mit-pre-commit"
version = "5.12.44"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
time = "0.3.7"
thiserror = "1.0.30"
miette = { version = "4.2.1", features = [ "fancy" ] }
clap_complete = "3.1.1"
clap = { version = "3.1.6", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
git2 = "0.14.2"
openssl = { version = "0.10.38", optional = true }
mit-commit = "3.1.1"



  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.44"

[features]
default = []
vendored-openssl = ["openssl/vendored"]


[dev-dependencies]
indoc = "1.0.4"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.44"
