[package]
name = "mit-pre-commit"
version = "3.11.0"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "Creative Commons Zero v1.0 Universal"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/pb-git-hooks"

[build-dependencies]
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"


[dependencies]
clap = "3.0.0-beta.1"
git2 = "0.13"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"

[dev-dependencies]
indoc = "0.3"
pretty_assertions = "0.6.1"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
