[package]
name = "mit-pre-commit"
version = "5.12.76"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
time = "0.3.12"
thiserror = "1.0.32"
miette = { version = "5.2.0", features = [ "fancy" ] }
clap_complete = "3.2.3"
clap = { version = "3.2.16", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
git2 = "0.14.4"
openssl = { version = "0.10.41", optional = true }
mit-commit = "3.1.2"



  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.12.76"

[features]
default = []
vendored-openssl = ["openssl/vendored"]


[dev-dependencies]
indoc = "1.0.7"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.12.76"
