[package]
name = "mit-pre-commit"
version = "5.11.9"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[dependencies]
time = "0.3.4"
thiserror = "1.0.30"
miette = { version = "3.2.0", features = [ "fancy" ] }
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
git2 = "0.13.23"
openssl = { version = "0.10.38", optional = true }
mit-commit = "3.0.0"



  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "5.11.9"

[features]
default = []
vendored-openssl = ["openssl/vendored"]


[dev-dependencies]
indoc = "1.0.3"


  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "5.11.9"
