[package]
name = "mit-pre-commit"
version = "3.99.6"
authors = [ "Billie Thompson <billie+mit-pre-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "Run first, before you even type in a commit message. It's used to inspect the snapshot that's about to be committed."
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "git", "git-hooks" ]
readme = "../README.md"
repository = "https://github.com/PurpleBooth/git-mit"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
tinytemplate = "1.2.1"
serde_json = "1.0.64"
serde_derive = "1.0.125"

  [build-dependencies.serde]
  version = "1.0.125"
  features = [ "derive" ]

  [build-dependencies.mit-build-tools]
  path = "../mit-build-tools"
  version = "3.99.6"

[dependencies]
thiserror = "1.0.25"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
git2 = "0.13.20"
mit-commit = "1.29.7"
console = "0.14.1"

  [dependencies.mit-commit-message-lints]
  path = "../mit-commit-message-lints"
  version = "3.99.6"

[dev-dependencies]
indoc = "1.0.3"
pretty_assertions = "0.7.2"

  [dev-dependencies.mit-hook-test-helper]
  path = "../mit-hook-test-helper"
  version = "3.99.6"
