name: automerge
on:
  pull_request:
    types:
      - opened
      - edited
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - ready_for_review
      - labeled 
      - unlabeled
      - synchronize
      - locked
      - unlocked 
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: rebase 
          MERGE_LABELS: dependencies 
          MERGE_RETRY_SLEEP: "100000"  
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: rebase 
          MERGE_LABELS: releases
          MERGE_RETRY_SLEEP: "100000"
          UPDATE_METHOD: rebase 
          UPDATE_LABELS: releases 
          UPDATE_RETRY_SLEEP: "100000"  
          UPDATE_RETRIES: 6
  automerge-label-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_RETRY_SLEEP: "100000"
          MERGE_LABELS: automerge-rebase
  automerge-label-squash:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_RETRY_SLEEP: "100000"
          MERGE_LABELS: automerge-squash
